### ISSUE TITLE
Incorrect sanity checks in `mzd_solve_left`?

### ISSUE THREAD

**Issue by j-danner** [malb/m4ri#21]
The function  `mzd_solve_left` has two sanity checks in its latest release; its documentation is as follows:
```c++
/**
 * \brief Solves A X = B with A and B matrices.
 *
 * The solution X is stored inplace on B.
 *
 * \param A Input matrix (overwritten).
 * \param B Input matrix, being overwritten by the solution matrix X
 * \param cutoff Minimal dimension for Strassen recursion (default: 0).
 * \param inconsistency_check decide wether or not to perform a check
 *        for incosistency (faster without but output not defined if
 *        system is not consistent).
 * \return 0 if a solution was found, -1 otherwise
 */
int mzd_solve_left(mzd_t *A, mzd_t *B, int const cutoff, int const inconsistency_check);
```

The sanity checks ensure that `A->ncols <= B->nrows ` and `A->nrows == B->nrows`.

As input let us consider a $n\times m$ matrix $A$ and a $l\times k$ matrix B, then the checks ensure $m\leq l$ and $n=l$.
In order to pass the checks we have to supply a matrix with exactly $l=n$ rows. So far so good.
However, if $m>n$, then the solution matrix $X$ has to be of size $m\times k$, and this matrix is too big to be stored in place in $B$. Looking at the source code there also seems to be no reallocation of `B`, hence the matrix $B$ has to be supplied with sufficient size, $\max(n,m)\times k$, to ensure enough space for $X$, but that violates the second sanity check introduced with commit 2a7363739004cc81a4b33c74082fff79ac3c800d.

I guess the second sanity check should be changed to `B->nrows == MAX(A->nrows, A->ncols)`, to allow solving linear systems $A\cdot X=B$ where $A$ has more columns than rows.

So my question is: Did I understand the documentation correctly, or is solving such a underdetermined system simply not supported?

**Comment by malb** [comment]
Mhhh, I don't see what it would mean to have `B->nrows > A->nrows`? If we wan to adopt the notation that we implicitly pad `A` and with zeroes then we should make this explicit. We'd also need to check that `B` has zeros in the bottom part, because otherwise the system isn't solvable?

**Comment by j-danner** [comment]
Well, yes you can also see this as an _implicitly zero-padded A_, that is an easier way to see it!
But with the current release one _cannot_ solve any system of linear equations with more indeterminates than equations without _explicitly_ padding  `A` and `B`; in prior releases it has been sufficient to just pad `B`, and I would strongly argue for keeping this a valid input.

As far as I see, the values padded in `B` are actually irrelevant since only the first `A->nrows` rows of `B` are used in the computation, the increased size is only necessary to fit the solution matrix $X$; so a check that the bottom part of `B` is zero could in theory be skipped. Nonetheless, I agree that a check would be good to avoid any accidental misuse of `mzd_solve_left`.

**Comment by malb** [comment]
That makes sense to me. My suggestion
- we're more explicit about this convention in the documentation
- we check that the bottom part of `B` iff `inconsistency_check = 1` 
- we add tests with `B`s bottom zeroed and non-zeroed

**Comment by j-danner** [comment]
Great, I have adapted the pull request correspondingly; after understanding it incorrectly at first...
